apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template: #inside your pod we are going to deploy our container workload
    metadata:
      labels:
        app: myapp 
    spec:
      containers:
      - name: myapp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80 #container port
        ##we will create name spaces in kubernetes
        #hard soft limiti
